// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/komminarlabs/pulumi-influxdb3/sdk/go/influxdb3/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The ID of the account that the cluster belongs to
func GetAccountId(ctx *pulumi.Context) string {
	return config.Get(ctx, "influxdb3:accountId")
}

// The ID of the cluster that you want to manage
func GetClusterId(ctx *pulumi.Context) string {
	return config.Get(ctx, "influxdb3:clusterId")
}

// The InfluxDB management token
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "influxdb3:token")
}

// The InfluxDB Cloud Dedicated Management API URL
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "influxdb3:url")
}
