// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB3
{
    public static class GetTokens
    {
        /// <summary>
        /// Gets all database tokens for a cluster.
        /// </summary>
        public static Task<GetTokensResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTokensResult>("influxdb3:index/getTokens:getTokens", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Gets all database tokens for a cluster.
        /// </summary>
        public static Output<GetTokensResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTokensResult>("influxdb3:index/getTokens:getTokens", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetTokensResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetTokensTokenResult> Tokens;

        [OutputConstructor]
        private GetTokensResult(
            string id,

            ImmutableArray<Outputs.GetTokensTokenResult> tokens)
        {
            Id = id;
            Tokens = tokens;
        }
    }
}
