// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("influxdb3");

/**
 * The ID of the account that the cluster belongs to
 */
export declare const accountId: string | undefined;
Object.defineProperty(exports, "accountId", {
    get() {
        return __config.get("accountId");
    },
    enumerable: true,
});

/**
 * The ID of the cluster that you want to manage
 */
export declare const clusterId: string | undefined;
Object.defineProperty(exports, "clusterId", {
    get() {
        return __config.get("clusterId");
    },
    enumerable: true,
});

/**
 * The InfluxDB management token
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

/**
 * The InfluxDB Cloud Dedicated Management API URL
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url");
    },
    enumerable: true,
});

