// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB3.Outputs
{

    [OutputType]
    public sealed class DatabasePartitionTemplate
    {
        /// <summary>
        /// The type of template part. Valid values are `bucket`, `tag` or `time`.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The value of template part. **Note:** For `bucket` partition template type use `jsonencode()` function to encode the value to a string.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private DatabasePartitionTemplate(
            string type,

            string value)
        {
            Type = type;
            Value = value;
        }
    }
}
