// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB3.Outputs
{

    [OutputType]
    public sealed class GetDatabasesDatabaseResult
    {
        /// <summary>
        /// The ID of the account that the cluster belongs to.
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// The ID of the cluster that you want to manage.
        /// </summary>
        public readonly string ClusterId;
        /// <summary>
        /// The maximum number of columns per table for the cluster database.
        /// </summary>
        public readonly int MaxColumnsPerTable;
        /// <summary>
        /// The maximum number of tables for the cluster database.
        /// </summary>
        public readonly int MaxTables;
        /// <summary>
        /// The name of the cluster database.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The template partitioning of the cluster database.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDatabasesDatabasePartitionTemplateResult> PartitionTemplates;
        /// <summary>
        /// The retention period of the cluster database in nanoseconds.
        /// </summary>
        public readonly int RetentionPeriod;

        [OutputConstructor]
        private GetDatabasesDatabaseResult(
            string accountId,

            string clusterId,

            int maxColumnsPerTable,

            int maxTables,

            string name,

            ImmutableArray<Outputs.GetDatabasesDatabasePartitionTemplateResult> partitionTemplates,

            int retentionPeriod)
        {
            AccountId = accountId;
            ClusterId = clusterId;
            MaxColumnsPerTable = maxColumnsPerTable;
            MaxTables = maxTables;
            Name = name;
            PartitionTemplates = partitionTemplates;
            RetentionPeriod = retentionPeriod;
        }
    }
}
