// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB3.Outputs
{

    [OutputType]
    public sealed class GetTokensTokenPermissionResult
    {
        /// <summary>
        /// The action the database token permission allows.
        /// </summary>
        public readonly string Action;
        /// <summary>
        /// The resource the database token permission applies to. `*` refers to all databases.
        /// </summary>
        public readonly string Resource;

        [OutputConstructor]
        private GetTokensTokenPermissionResult(
            string action,

            string resource)
        {
            Action = action;
            Resource = resource;
        }
    }
}
