// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB3.Outputs
{

    [OutputType]
    public sealed class GetTokensTokenResult
    {
        /// <summary>
        /// The access token that can be used to authenticate query and write requests to the cluster. The access token is never stored by InfluxDB and is only returned once when the token is created. If the access token is lost, a new token must be created.
        /// </summary>
        public readonly string AccessToken;
        /// <summary>
        /// The ID of the account that the database token belongs to.
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// The ID of the cluster that the database token belongs to.
        /// </summary>
        public readonly string ClusterId;
        /// <summary>
        /// The date and time that the database token was created. Uses RFC3339 format.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The description of the database token.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The ID of the database token.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of permissions the database token allows.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetTokensTokenPermissionResult> Permissions;

        [OutputConstructor]
        private GetTokensTokenResult(
            string accessToken,

            string accountId,

            string clusterId,

            string createdAt,

            string description,

            string id,

            ImmutableArray<Outputs.GetTokensTokenPermissionResult> permissions)
        {
            AccessToken = accessToken;
            AccountId = accountId;
            ClusterId = clusterId;
            CreatedAt = createdAt;
            Description = description;
            Id = id;
            Permissions = permissions;
        }
    }
}
