// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package influxdb3

import (
	"context"
	"reflect"

	"github.com/komminarlabs/pulumi-influxdb3/sdk/go/influxdb3/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Gets all database tokens for a cluster.
func GetTokens(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetTokensResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTokensResult
	err := ctx.Invoke("influxdb3:index/getTokens:getTokens", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getTokens.
type GetTokensResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id     string           `pulumi:"id"`
	Tokens []GetTokensToken `pulumi:"tokens"`
}

func GetTokensOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetTokensResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetTokensResult, error) {
		r, err := GetTokens(ctx, opts...)
		var s GetTokensResult
		if r != nil {
			s = *r
		}
		return s, err
	}).(GetTokensResultOutput)
}

// A collection of values returned by getTokens.
type GetTokensResultOutput struct{ *pulumi.OutputState }

func (GetTokensResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokensResult)(nil)).Elem()
}

func (o GetTokensResultOutput) ToGetTokensResultOutput() GetTokensResultOutput {
	return o
}

func (o GetTokensResultOutput) ToGetTokensResultOutputWithContext(ctx context.Context) GetTokensResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetTokensResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokensResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTokensResultOutput) Tokens() GetTokensTokenArrayOutput {
	return o.ApplyT(func(v GetTokensResult) []GetTokensToken { return v.Tokens }).(GetTokensTokenArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTokensResultOutput{})
}
