// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package influxdb3

import (
	"context"
	"reflect"

	"github.com/komminarlabs/pulumi-influxdb3/sdk/go/influxdb3/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type TokenPermission struct {
	// The action the database token permission allows. Valid values are `read` or `write`.
	Action string `pulumi:"action"`
	// The resource the database token permission applies to. `*` refers to all databases.
	Resource string `pulumi:"resource"`
}

// TokenPermissionInput is an input type that accepts TokenPermissionArgs and TokenPermissionOutput values.
// You can construct a concrete instance of `TokenPermissionInput` via:
//
//	TokenPermissionArgs{...}
type TokenPermissionInput interface {
	pulumi.Input

	ToTokenPermissionOutput() TokenPermissionOutput
	ToTokenPermissionOutputWithContext(context.Context) TokenPermissionOutput
}

type TokenPermissionArgs struct {
	// The action the database token permission allows. Valid values are `read` or `write`.
	Action pulumi.StringInput `pulumi:"action"`
	// The resource the database token permission applies to. `*` refers to all databases.
	Resource pulumi.StringInput `pulumi:"resource"`
}

func (TokenPermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenPermission)(nil)).Elem()
}

func (i TokenPermissionArgs) ToTokenPermissionOutput() TokenPermissionOutput {
	return i.ToTokenPermissionOutputWithContext(context.Background())
}

func (i TokenPermissionArgs) ToTokenPermissionOutputWithContext(ctx context.Context) TokenPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenPermissionOutput)
}

// TokenPermissionArrayInput is an input type that accepts TokenPermissionArray and TokenPermissionArrayOutput values.
// You can construct a concrete instance of `TokenPermissionArrayInput` via:
//
//	TokenPermissionArray{ TokenPermissionArgs{...} }
type TokenPermissionArrayInput interface {
	pulumi.Input

	ToTokenPermissionArrayOutput() TokenPermissionArrayOutput
	ToTokenPermissionArrayOutputWithContext(context.Context) TokenPermissionArrayOutput
}

type TokenPermissionArray []TokenPermissionInput

func (TokenPermissionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TokenPermission)(nil)).Elem()
}

func (i TokenPermissionArray) ToTokenPermissionArrayOutput() TokenPermissionArrayOutput {
	return i.ToTokenPermissionArrayOutputWithContext(context.Background())
}

func (i TokenPermissionArray) ToTokenPermissionArrayOutputWithContext(ctx context.Context) TokenPermissionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenPermissionArrayOutput)
}

type TokenPermissionOutput struct{ *pulumi.OutputState }

func (TokenPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TokenPermission)(nil)).Elem()
}

func (o TokenPermissionOutput) ToTokenPermissionOutput() TokenPermissionOutput {
	return o
}

func (o TokenPermissionOutput) ToTokenPermissionOutputWithContext(ctx context.Context) TokenPermissionOutput {
	return o
}

// The action the database token permission allows. Valid values are `read` or `write`.
func (o TokenPermissionOutput) Action() pulumi.StringOutput {
	return o.ApplyT(func(v TokenPermission) string { return v.Action }).(pulumi.StringOutput)
}

// The resource the database token permission applies to. `*` refers to all databases.
func (o TokenPermissionOutput) Resource() pulumi.StringOutput {
	return o.ApplyT(func(v TokenPermission) string { return v.Resource }).(pulumi.StringOutput)
}

type TokenPermissionArrayOutput struct{ *pulumi.OutputState }

func (TokenPermissionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TokenPermission)(nil)).Elem()
}

func (o TokenPermissionArrayOutput) ToTokenPermissionArrayOutput() TokenPermissionArrayOutput {
	return o
}

func (o TokenPermissionArrayOutput) ToTokenPermissionArrayOutputWithContext(ctx context.Context) TokenPermissionArrayOutput {
	return o
}

func (o TokenPermissionArrayOutput) Index(i pulumi.IntInput) TokenPermissionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) TokenPermission {
		return vs[0].([]TokenPermission)[vs[1].(int)]
	}).(TokenPermissionOutput)
}

type GetDatabasesDatabase struct {
	// The ID of the account that the cluster belongs to.
	AccountId string `pulumi:"accountId"`
	// The ID of the cluster that you want to manage.
	ClusterId string `pulumi:"clusterId"`
	// The maximum number of columns per table for the cluster database.
	MaxColumnsPerTable int `pulumi:"maxColumnsPerTable"`
	// The maximum number of tables for the cluster database.
	MaxTables int `pulumi:"maxTables"`
	// The name of the cluster database.
	Name string `pulumi:"name"`
	// The retention period of the cluster database in nanoseconds.
	RetentionPeriod int `pulumi:"retentionPeriod"`
}

// GetDatabasesDatabaseInput is an input type that accepts GetDatabasesDatabaseArgs and GetDatabasesDatabaseOutput values.
// You can construct a concrete instance of `GetDatabasesDatabaseInput` via:
//
//	GetDatabasesDatabaseArgs{...}
type GetDatabasesDatabaseInput interface {
	pulumi.Input

	ToGetDatabasesDatabaseOutput() GetDatabasesDatabaseOutput
	ToGetDatabasesDatabaseOutputWithContext(context.Context) GetDatabasesDatabaseOutput
}

type GetDatabasesDatabaseArgs struct {
	// The ID of the account that the cluster belongs to.
	AccountId pulumi.StringInput `pulumi:"accountId"`
	// The ID of the cluster that you want to manage.
	ClusterId pulumi.StringInput `pulumi:"clusterId"`
	// The maximum number of columns per table for the cluster database.
	MaxColumnsPerTable pulumi.IntInput `pulumi:"maxColumnsPerTable"`
	// The maximum number of tables for the cluster database.
	MaxTables pulumi.IntInput `pulumi:"maxTables"`
	// The name of the cluster database.
	Name pulumi.StringInput `pulumi:"name"`
	// The retention period of the cluster database in nanoseconds.
	RetentionPeriod pulumi.IntInput `pulumi:"retentionPeriod"`
}

func (GetDatabasesDatabaseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDatabasesDatabase)(nil)).Elem()
}

func (i GetDatabasesDatabaseArgs) ToGetDatabasesDatabaseOutput() GetDatabasesDatabaseOutput {
	return i.ToGetDatabasesDatabaseOutputWithContext(context.Background())
}

func (i GetDatabasesDatabaseArgs) ToGetDatabasesDatabaseOutputWithContext(ctx context.Context) GetDatabasesDatabaseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDatabasesDatabaseOutput)
}

// GetDatabasesDatabaseArrayInput is an input type that accepts GetDatabasesDatabaseArray and GetDatabasesDatabaseArrayOutput values.
// You can construct a concrete instance of `GetDatabasesDatabaseArrayInput` via:
//
//	GetDatabasesDatabaseArray{ GetDatabasesDatabaseArgs{...} }
type GetDatabasesDatabaseArrayInput interface {
	pulumi.Input

	ToGetDatabasesDatabaseArrayOutput() GetDatabasesDatabaseArrayOutput
	ToGetDatabasesDatabaseArrayOutputWithContext(context.Context) GetDatabasesDatabaseArrayOutput
}

type GetDatabasesDatabaseArray []GetDatabasesDatabaseInput

func (GetDatabasesDatabaseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDatabasesDatabase)(nil)).Elem()
}

func (i GetDatabasesDatabaseArray) ToGetDatabasesDatabaseArrayOutput() GetDatabasesDatabaseArrayOutput {
	return i.ToGetDatabasesDatabaseArrayOutputWithContext(context.Background())
}

func (i GetDatabasesDatabaseArray) ToGetDatabasesDatabaseArrayOutputWithContext(ctx context.Context) GetDatabasesDatabaseArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDatabasesDatabaseArrayOutput)
}

type GetDatabasesDatabaseOutput struct{ *pulumi.OutputState }

func (GetDatabasesDatabaseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDatabasesDatabase)(nil)).Elem()
}

func (o GetDatabasesDatabaseOutput) ToGetDatabasesDatabaseOutput() GetDatabasesDatabaseOutput {
	return o
}

func (o GetDatabasesDatabaseOutput) ToGetDatabasesDatabaseOutputWithContext(ctx context.Context) GetDatabasesDatabaseOutput {
	return o
}

// The ID of the account that the cluster belongs to.
func (o GetDatabasesDatabaseOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabasesDatabase) string { return v.AccountId }).(pulumi.StringOutput)
}

// The ID of the cluster that you want to manage.
func (o GetDatabasesDatabaseOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabasesDatabase) string { return v.ClusterId }).(pulumi.StringOutput)
}

// The maximum number of columns per table for the cluster database.
func (o GetDatabasesDatabaseOutput) MaxColumnsPerTable() pulumi.IntOutput {
	return o.ApplyT(func(v GetDatabasesDatabase) int { return v.MaxColumnsPerTable }).(pulumi.IntOutput)
}

// The maximum number of tables for the cluster database.
func (o GetDatabasesDatabaseOutput) MaxTables() pulumi.IntOutput {
	return o.ApplyT(func(v GetDatabasesDatabase) int { return v.MaxTables }).(pulumi.IntOutput)
}

// The name of the cluster database.
func (o GetDatabasesDatabaseOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDatabasesDatabase) string { return v.Name }).(pulumi.StringOutput)
}

// The retention period of the cluster database in nanoseconds.
func (o GetDatabasesDatabaseOutput) RetentionPeriod() pulumi.IntOutput {
	return o.ApplyT(func(v GetDatabasesDatabase) int { return v.RetentionPeriod }).(pulumi.IntOutput)
}

type GetDatabasesDatabaseArrayOutput struct{ *pulumi.OutputState }

func (GetDatabasesDatabaseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDatabasesDatabase)(nil)).Elem()
}

func (o GetDatabasesDatabaseArrayOutput) ToGetDatabasesDatabaseArrayOutput() GetDatabasesDatabaseArrayOutput {
	return o
}

func (o GetDatabasesDatabaseArrayOutput) ToGetDatabasesDatabaseArrayOutputWithContext(ctx context.Context) GetDatabasesDatabaseArrayOutput {
	return o
}

func (o GetDatabasesDatabaseArrayOutput) Index(i pulumi.IntInput) GetDatabasesDatabaseOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetDatabasesDatabase {
		return vs[0].([]GetDatabasesDatabase)[vs[1].(int)]
	}).(GetDatabasesDatabaseOutput)
}

type GetTokenPermission struct {
	// The action the database token permission allows.
	Action string `pulumi:"action"`
	// The resource the database token permission applies to. `*` refers to all databases.
	Resource string `pulumi:"resource"`
}

// GetTokenPermissionInput is an input type that accepts GetTokenPermissionArgs and GetTokenPermissionOutput values.
// You can construct a concrete instance of `GetTokenPermissionInput` via:
//
//	GetTokenPermissionArgs{...}
type GetTokenPermissionInput interface {
	pulumi.Input

	ToGetTokenPermissionOutput() GetTokenPermissionOutput
	ToGetTokenPermissionOutputWithContext(context.Context) GetTokenPermissionOutput
}

type GetTokenPermissionArgs struct {
	// The action the database token permission allows.
	Action pulumi.StringInput `pulumi:"action"`
	// The resource the database token permission applies to. `*` refers to all databases.
	Resource pulumi.StringInput `pulumi:"resource"`
}

func (GetTokenPermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokenPermission)(nil)).Elem()
}

func (i GetTokenPermissionArgs) ToGetTokenPermissionOutput() GetTokenPermissionOutput {
	return i.ToGetTokenPermissionOutputWithContext(context.Background())
}

func (i GetTokenPermissionArgs) ToGetTokenPermissionOutputWithContext(ctx context.Context) GetTokenPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTokenPermissionOutput)
}

// GetTokenPermissionArrayInput is an input type that accepts GetTokenPermissionArray and GetTokenPermissionArrayOutput values.
// You can construct a concrete instance of `GetTokenPermissionArrayInput` via:
//
//	GetTokenPermissionArray{ GetTokenPermissionArgs{...} }
type GetTokenPermissionArrayInput interface {
	pulumi.Input

	ToGetTokenPermissionArrayOutput() GetTokenPermissionArrayOutput
	ToGetTokenPermissionArrayOutputWithContext(context.Context) GetTokenPermissionArrayOutput
}

type GetTokenPermissionArray []GetTokenPermissionInput

func (GetTokenPermissionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTokenPermission)(nil)).Elem()
}

func (i GetTokenPermissionArray) ToGetTokenPermissionArrayOutput() GetTokenPermissionArrayOutput {
	return i.ToGetTokenPermissionArrayOutputWithContext(context.Background())
}

func (i GetTokenPermissionArray) ToGetTokenPermissionArrayOutputWithContext(ctx context.Context) GetTokenPermissionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTokenPermissionArrayOutput)
}

type GetTokenPermissionOutput struct{ *pulumi.OutputState }

func (GetTokenPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokenPermission)(nil)).Elem()
}

func (o GetTokenPermissionOutput) ToGetTokenPermissionOutput() GetTokenPermissionOutput {
	return o
}

func (o GetTokenPermissionOutput) ToGetTokenPermissionOutputWithContext(ctx context.Context) GetTokenPermissionOutput {
	return o
}

// The action the database token permission allows.
func (o GetTokenPermissionOutput) Action() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenPermission) string { return v.Action }).(pulumi.StringOutput)
}

// The resource the database token permission applies to. `*` refers to all databases.
func (o GetTokenPermissionOutput) Resource() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokenPermission) string { return v.Resource }).(pulumi.StringOutput)
}

type GetTokenPermissionArrayOutput struct{ *pulumi.OutputState }

func (GetTokenPermissionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTokenPermission)(nil)).Elem()
}

func (o GetTokenPermissionArrayOutput) ToGetTokenPermissionArrayOutput() GetTokenPermissionArrayOutput {
	return o
}

func (o GetTokenPermissionArrayOutput) ToGetTokenPermissionArrayOutputWithContext(ctx context.Context) GetTokenPermissionArrayOutput {
	return o
}

func (o GetTokenPermissionArrayOutput) Index(i pulumi.IntInput) GetTokenPermissionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTokenPermission {
		return vs[0].([]GetTokenPermission)[vs[1].(int)]
	}).(GetTokenPermissionOutput)
}

type GetTokensToken struct {
	// The access token that can be used to authenticate query and write requests to the cluster. The access token is never stored by InfluxDB and is only returned once when the token is created. If the access token is lost, a new token must be created.
	AccessToken string `pulumi:"accessToken"`
	// The ID of the account that the database token belongs to.
	AccountId string `pulumi:"accountId"`
	// The ID of the cluster that the database token belongs to.
	ClusterId string `pulumi:"clusterId"`
	// The date and time that the database token was created. Uses RFC3339 format.
	CreatedAt string `pulumi:"createdAt"`
	// The description of the database token.
	Description string `pulumi:"description"`
	// The ID of the database token.
	Id string `pulumi:"id"`
	// The list of permissions the database token allows.
	Permissions []GetTokensTokenPermission `pulumi:"permissions"`
}

// GetTokensTokenInput is an input type that accepts GetTokensTokenArgs and GetTokensTokenOutput values.
// You can construct a concrete instance of `GetTokensTokenInput` via:
//
//	GetTokensTokenArgs{...}
type GetTokensTokenInput interface {
	pulumi.Input

	ToGetTokensTokenOutput() GetTokensTokenOutput
	ToGetTokensTokenOutputWithContext(context.Context) GetTokensTokenOutput
}

type GetTokensTokenArgs struct {
	// The access token that can be used to authenticate query and write requests to the cluster. The access token is never stored by InfluxDB and is only returned once when the token is created. If the access token is lost, a new token must be created.
	AccessToken pulumi.StringInput `pulumi:"accessToken"`
	// The ID of the account that the database token belongs to.
	AccountId pulumi.StringInput `pulumi:"accountId"`
	// The ID of the cluster that the database token belongs to.
	ClusterId pulumi.StringInput `pulumi:"clusterId"`
	// The date and time that the database token was created. Uses RFC3339 format.
	CreatedAt pulumi.StringInput `pulumi:"createdAt"`
	// The description of the database token.
	Description pulumi.StringInput `pulumi:"description"`
	// The ID of the database token.
	Id pulumi.StringInput `pulumi:"id"`
	// The list of permissions the database token allows.
	Permissions GetTokensTokenPermissionArrayInput `pulumi:"permissions"`
}

func (GetTokensTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokensToken)(nil)).Elem()
}

func (i GetTokensTokenArgs) ToGetTokensTokenOutput() GetTokensTokenOutput {
	return i.ToGetTokensTokenOutputWithContext(context.Background())
}

func (i GetTokensTokenArgs) ToGetTokensTokenOutputWithContext(ctx context.Context) GetTokensTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTokensTokenOutput)
}

// GetTokensTokenArrayInput is an input type that accepts GetTokensTokenArray and GetTokensTokenArrayOutput values.
// You can construct a concrete instance of `GetTokensTokenArrayInput` via:
//
//	GetTokensTokenArray{ GetTokensTokenArgs{...} }
type GetTokensTokenArrayInput interface {
	pulumi.Input

	ToGetTokensTokenArrayOutput() GetTokensTokenArrayOutput
	ToGetTokensTokenArrayOutputWithContext(context.Context) GetTokensTokenArrayOutput
}

type GetTokensTokenArray []GetTokensTokenInput

func (GetTokensTokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTokensToken)(nil)).Elem()
}

func (i GetTokensTokenArray) ToGetTokensTokenArrayOutput() GetTokensTokenArrayOutput {
	return i.ToGetTokensTokenArrayOutputWithContext(context.Background())
}

func (i GetTokensTokenArray) ToGetTokensTokenArrayOutputWithContext(ctx context.Context) GetTokensTokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTokensTokenArrayOutput)
}

type GetTokensTokenOutput struct{ *pulumi.OutputState }

func (GetTokensTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokensToken)(nil)).Elem()
}

func (o GetTokensTokenOutput) ToGetTokensTokenOutput() GetTokensTokenOutput {
	return o
}

func (o GetTokensTokenOutput) ToGetTokensTokenOutputWithContext(ctx context.Context) GetTokensTokenOutput {
	return o
}

// The access token that can be used to authenticate query and write requests to the cluster. The access token is never stored by InfluxDB and is only returned once when the token is created. If the access token is lost, a new token must be created.
func (o GetTokensTokenOutput) AccessToken() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokensToken) string { return v.AccessToken }).(pulumi.StringOutput)
}

// The ID of the account that the database token belongs to.
func (o GetTokensTokenOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokensToken) string { return v.AccountId }).(pulumi.StringOutput)
}

// The ID of the cluster that the database token belongs to.
func (o GetTokensTokenOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokensToken) string { return v.ClusterId }).(pulumi.StringOutput)
}

// The date and time that the database token was created. Uses RFC3339 format.
func (o GetTokensTokenOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokensToken) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The description of the database token.
func (o GetTokensTokenOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokensToken) string { return v.Description }).(pulumi.StringOutput)
}

// The ID of the database token.
func (o GetTokensTokenOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokensToken) string { return v.Id }).(pulumi.StringOutput)
}

// The list of permissions the database token allows.
func (o GetTokensTokenOutput) Permissions() GetTokensTokenPermissionArrayOutput {
	return o.ApplyT(func(v GetTokensToken) []GetTokensTokenPermission { return v.Permissions }).(GetTokensTokenPermissionArrayOutput)
}

type GetTokensTokenArrayOutput struct{ *pulumi.OutputState }

func (GetTokensTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTokensToken)(nil)).Elem()
}

func (o GetTokensTokenArrayOutput) ToGetTokensTokenArrayOutput() GetTokensTokenArrayOutput {
	return o
}

func (o GetTokensTokenArrayOutput) ToGetTokensTokenArrayOutputWithContext(ctx context.Context) GetTokensTokenArrayOutput {
	return o
}

func (o GetTokensTokenArrayOutput) Index(i pulumi.IntInput) GetTokensTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTokensToken {
		return vs[0].([]GetTokensToken)[vs[1].(int)]
	}).(GetTokensTokenOutput)
}

type GetTokensTokenPermission struct {
	// The action the database token permission allows.
	Action string `pulumi:"action"`
	// The resource the database token permission applies to. `*` refers to all databases.
	Resource string `pulumi:"resource"`
}

// GetTokensTokenPermissionInput is an input type that accepts GetTokensTokenPermissionArgs and GetTokensTokenPermissionOutput values.
// You can construct a concrete instance of `GetTokensTokenPermissionInput` via:
//
//	GetTokensTokenPermissionArgs{...}
type GetTokensTokenPermissionInput interface {
	pulumi.Input

	ToGetTokensTokenPermissionOutput() GetTokensTokenPermissionOutput
	ToGetTokensTokenPermissionOutputWithContext(context.Context) GetTokensTokenPermissionOutput
}

type GetTokensTokenPermissionArgs struct {
	// The action the database token permission allows.
	Action pulumi.StringInput `pulumi:"action"`
	// The resource the database token permission applies to. `*` refers to all databases.
	Resource pulumi.StringInput `pulumi:"resource"`
}

func (GetTokensTokenPermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokensTokenPermission)(nil)).Elem()
}

func (i GetTokensTokenPermissionArgs) ToGetTokensTokenPermissionOutput() GetTokensTokenPermissionOutput {
	return i.ToGetTokensTokenPermissionOutputWithContext(context.Background())
}

func (i GetTokensTokenPermissionArgs) ToGetTokensTokenPermissionOutputWithContext(ctx context.Context) GetTokensTokenPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTokensTokenPermissionOutput)
}

// GetTokensTokenPermissionArrayInput is an input type that accepts GetTokensTokenPermissionArray and GetTokensTokenPermissionArrayOutput values.
// You can construct a concrete instance of `GetTokensTokenPermissionArrayInput` via:
//
//	GetTokensTokenPermissionArray{ GetTokensTokenPermissionArgs{...} }
type GetTokensTokenPermissionArrayInput interface {
	pulumi.Input

	ToGetTokensTokenPermissionArrayOutput() GetTokensTokenPermissionArrayOutput
	ToGetTokensTokenPermissionArrayOutputWithContext(context.Context) GetTokensTokenPermissionArrayOutput
}

type GetTokensTokenPermissionArray []GetTokensTokenPermissionInput

func (GetTokensTokenPermissionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTokensTokenPermission)(nil)).Elem()
}

func (i GetTokensTokenPermissionArray) ToGetTokensTokenPermissionArrayOutput() GetTokensTokenPermissionArrayOutput {
	return i.ToGetTokensTokenPermissionArrayOutputWithContext(context.Background())
}

func (i GetTokensTokenPermissionArray) ToGetTokensTokenPermissionArrayOutputWithContext(ctx context.Context) GetTokensTokenPermissionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTokensTokenPermissionArrayOutput)
}

type GetTokensTokenPermissionOutput struct{ *pulumi.OutputState }

func (GetTokensTokenPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTokensTokenPermission)(nil)).Elem()
}

func (o GetTokensTokenPermissionOutput) ToGetTokensTokenPermissionOutput() GetTokensTokenPermissionOutput {
	return o
}

func (o GetTokensTokenPermissionOutput) ToGetTokensTokenPermissionOutputWithContext(ctx context.Context) GetTokensTokenPermissionOutput {
	return o
}

// The action the database token permission allows.
func (o GetTokensTokenPermissionOutput) Action() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokensTokenPermission) string { return v.Action }).(pulumi.StringOutput)
}

// The resource the database token permission applies to. `*` refers to all databases.
func (o GetTokensTokenPermissionOutput) Resource() pulumi.StringOutput {
	return o.ApplyT(func(v GetTokensTokenPermission) string { return v.Resource }).(pulumi.StringOutput)
}

type GetTokensTokenPermissionArrayOutput struct{ *pulumi.OutputState }

func (GetTokensTokenPermissionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTokensTokenPermission)(nil)).Elem()
}

func (o GetTokensTokenPermissionArrayOutput) ToGetTokensTokenPermissionArrayOutput() GetTokensTokenPermissionArrayOutput {
	return o
}

func (o GetTokensTokenPermissionArrayOutput) ToGetTokensTokenPermissionArrayOutputWithContext(ctx context.Context) GetTokensTokenPermissionArrayOutput {
	return o
}

func (o GetTokensTokenPermissionArrayOutput) Index(i pulumi.IntInput) GetTokensTokenPermissionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTokensTokenPermission {
		return vs[0].([]GetTokensTokenPermission)[vs[1].(int)]
	}).(GetTokensTokenPermissionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TokenPermissionInput)(nil)).Elem(), TokenPermissionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenPermissionArrayInput)(nil)).Elem(), TokenPermissionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDatabasesDatabaseInput)(nil)).Elem(), GetDatabasesDatabaseArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDatabasesDatabaseArrayInput)(nil)).Elem(), GetDatabasesDatabaseArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTokenPermissionInput)(nil)).Elem(), GetTokenPermissionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTokenPermissionArrayInput)(nil)).Elem(), GetTokenPermissionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTokensTokenInput)(nil)).Elem(), GetTokensTokenArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTokensTokenArrayInput)(nil)).Elem(), GetTokensTokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTokensTokenPermissionInput)(nil)).Elem(), GetTokensTokenPermissionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTokensTokenPermissionArrayInput)(nil)).Elem(), GetTokensTokenPermissionArray{})
	pulumi.RegisterOutputType(TokenPermissionOutput{})
	pulumi.RegisterOutputType(TokenPermissionArrayOutput{})
	pulumi.RegisterOutputType(GetDatabasesDatabaseOutput{})
	pulumi.RegisterOutputType(GetDatabasesDatabaseArrayOutput{})
	pulumi.RegisterOutputType(GetTokenPermissionOutput{})
	pulumi.RegisterOutputType(GetTokenPermissionArrayOutput{})
	pulumi.RegisterOutputType(GetTokensTokenOutput{})
	pulumi.RegisterOutputType(GetTokensTokenArrayOutput{})
	pulumi.RegisterOutputType(GetTokensTokenPermissionOutput{})
	pulumi.RegisterOutputType(GetTokensTokenPermissionArrayOutput{})
}
