# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

accountId: Optional[str]
"""
The ID of the account that the cluster belongs to
"""

clusterId: Optional[str]
"""
The ID of the cluster that you want to manage
"""

token: Optional[str]
"""
The InfluxDB management token
"""

url: Optional[str]
"""
The InfluxDB Cloud Dedicated Management API URL
"""

