// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface TokenPermission {
    /**
     * The action the database token permission allows. Valid values are `read` or `write`.
     */
    action: pulumi.Input<string>;
    /**
     * The resource the database token permission applies to. `*` refers to all databases.
     */
    resource: pulumi.Input<string>;
}
