// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace KomminarLabs.InfluxDB3.Inputs
{

    public sealed class DatabasePartitionTemplateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The type of template part. Valid values are `bucket`, `tag` or `time`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// The value of template part. **Note:** For `bucket` partition template type use `jsonencode()` function to encode the value to a string.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public DatabasePartitionTemplateArgs()
        {
        }
        public static new DatabasePartitionTemplateArgs Empty => new DatabasePartitionTemplateArgs();
    }
}
